abstractPath: abstract.tex
submissionTitle: Two Components Are Not Connected
submissionSlug: TwoComponentsNotConnected
statementLakefilePath: statement-package/lakefile.lean
statementLeanToolchainPath: statement-package/lean-toolchain
proofLakefilePath: lakefile.lean
proofLeanToolchainPath: lean-toolchain
bibtex-entries:
  - |
    @inbook{Diestel2017Connectivity,
      author = {Diestel, Reinhard},
      title = {Connectivity},
      booktitle = {Graph Theory},
      series = {Graduate Texts in Mathematics},
      volume = {173},
      publisher = {Springer Berlin Heidelberg},
      address = {Berlin, Heidelberg},
      year = {2017},
      pages = {59--87},
      isbn = {978-3-662-53622-3},
      doi = {10.1007/978-3-662-53622-3_3},
      url = {https://doi.org/10.1007/978-3-662-53622-3_3}
    }
statements:
  - Name: ConnectedRelation
    Type: Definition
    Statement:
      CurrentSubmission: true
      LeanStatement: statement-package/TwoComponentsNotConnected/Statements/ConnectedRelation.lean
      LatexDefinition: statement-package/TwoComponentsNotConnected/Statements/ConnectedRelation.tex
      Name: TwoComponentsNotConnected.Statements.ConnectedRelation.IsConnectedRelation
    DeclarationReferences: []
  - Name: TwoComponentsDisconnected
    Type: Axiom
    Statement:
      CurrentSubmission: true
      LeanStatement: statement-package/TwoComponentsNotConnected/Statements/TwoComponentsDisconnected.lean
      LatexDefinition: statement-package/TwoComponentsNotConnected/Statements/TwoComponentsDisconnected.tex
      Name: TwoComponentsNotConnected.Statements.TwoComponentsDisconnected.two_components_not_connected
    DeclarationReferences:
      - CurrentSubmission: true
        LeanStatement: statement-package/TwoComponentsNotConnected/Statements/ConnectedRelation.lean
        LatexDefinition: statement-package/TwoComponentsNotConnected/Statements/ConnectedRelation.tex
        Name: TwoComponentsNotConnected.Statements.ConnectedRelation.IsConnectedRelation
proofs:
  - Name: TwoComponentsDisconnectedProof
    Type: proof
    Theorem:
      CurrentSubmission: true
      LeanStatement: statement-package/TwoComponentsNotConnected/Statements/TwoComponentsDisconnected.lean
      LatexDefinition: statement-package/TwoComponentsNotConnected/Statements/TwoComponentsDisconnected.tex
      Name: TwoComponentsNotConnected.Statements.TwoComponentsDisconnected.two_components_not_connected
    Proof:
      File: proofs/TwoComponentsNotConnected/Proofs/TwoComponentsDisconnectedProof.lean
      Name: TwoComponentsNotConnected.Proofs.TwoComponentsDisconnected.two_components_not_connected
    DeclarationReferences:
      - CurrentSubmission: true
        LeanStatement: statement-package/TwoComponentsNotConnected/Statements/ConnectedRelation.lean
        LatexDefinition: statement-package/TwoComponentsNotConnected/Statements/ConnectedRelation.tex
        Name: TwoComponentsNotConnected.Statements.ConnectedRelation.IsConnectedRelation
